### ISSUE TITLE
Cambios 26/05/2015

### ISSUE THREAD

**Issue by PabloI13** [jmirancid/TropicalNet.Topppro#22]
Hay que cambiar de lugar:
- AVANTI a SPEAKERS (pa systems) a continuación de X Series (por ahora)

Cambiar orden:
En X Series (speakers) empezar con X CS 12 y X CS 15, despues el resto.

Se pasan a Legacy los siguientes productos:
- TAC-MICPRE-ARK (modules)
- GIG-PACKS: 8250 / 6250 / 4200 (pa systems)

Sacar directamente:
- E-CS (module) Obviamente eliminar la imagen de los módulos.

Mixers
Poner primero T20 en mixers, 2do lugar para DMX.

**Comment by jmirancid** [comment]
Cerrado.
