### ISSUE TITLE
Detail producto 26/05/2015

### ISSUE THREAD

**Issue by PabloI13** [jmirancid/TropicalNet.Topppro#23]
Peter quiere subir los accesos a Hi Res y User´s Manual arriba de las tablas, dice que debajo se pierden y hay que ir hasta el final para ver que están ahí. (creo que tiene razón)

Entonces quedaría:

El título /
Header /
User´s Manual / Hi Res Images
Tabla /

**Comment by jmirancid** [comment]
Cerrado.
